volumes:
  parser_pgadmin: {}
networks:
  parser-net:
    driver: bridge
services:
  redis:
    container_name: parser-redis
    image: "redis:alpine"
    networks:
      - parser-net
    logging:
      driver: none

  postgres:
    container_name: parser-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES="parser-postgres"
    networks:
      - parser-net
    logging:
      driver: none

  pgadmin:
    container_name: parser-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mymap.online}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - parser_pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5051}:80'
    networks:
      - parser-net
    restart: unless-stopped
    logging:
      driver: none
