version: "3.9"
volumes:
  parser_pgadmin: {}
services:
  redis:
    container_name: parser-redis
    image: "redis:alpine"
    logging:
      driver: none

  postgres:
    container_name: parser-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES="parser-redis"
    logging:
      driver: none

  pgadmin:
    container_name: emd-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mymap.online}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_common:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5051}:80'
    restart: unless-stopped
    logging:
      driver: none
